name: Build & Package MQ5 EAs

on:
  push:
    branches: [main, master]
  workflow_dispatch:         # manual trigger button

concurrency: build-ea-${{ github.ref }}   # cancel previous build on same branch

jobs:
  build:
    runs-on: [self-hosted, crossover, mt5]

    steps:
      - uses: actions/checkout@v4

      - name: Compile all MQ5 sources
        run: ./scripts/compile.sh

      - name: Upload compiled EAs
        uses: actions/upload-artifact@v4
        with:
          name: EA-binaries
          path: Experts/*.ex5
          retention-days: 14          # keep artefacts 2 weeks
