name: CI – MQL5 compile check

on:
  workflow_dispatch:      # manual trigger button
  pull_request:           # runs when a PR is opened/updated
    paths:
      - '**/*.mq5'

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fx31337/mql-compile-action@v2
        with:
          init-platform: true        # ← download portable MT5
          path: '.'                  # compile every .mq5
          include: '.'               # look for .mqh includes here
          syntax-only: true          # stop after syntax check
          verbose: true
