name: CI – MQL5 compile check

on:
  workflow_dispatch:       # manual “Run workflow” button
  pull_request:            # compile when a PR touches a .mq5
    paths:
      - '**/*.mq5'

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fx31337/mql-compile-action@v2
        with:
          init-platform: true   # download & unpack portable MT5
          path: '.'            # compile every .mq5 in the repo
          include: '.'         # search .mqh includes here
          syntax-only: true    # just a syntax check (no .ex5 saved)
          verbose: true
