name: CI – MQL5 compile check

on:
  workflow_dispatch:        # manual button
  pull_request:             # run on PRs that touch .mq5
    paths:
      - '**/*.mq5'

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fx31337/mql-compile-action@v2
        with:
          init-platform: true        # download portable MT5
          mt-path: mt5-platform      # <─ where to put it (relative path)
          path: '.'                  # compile every .mq5 in repo
          include: '.'               # look for .mqh includes here
          syntax-only: true          # just a syntax check
          verbose: true
