name: CI – MQL5 compile check                # appears in the Actions tab

on:
  workflow_dispatch:                         # manual “Run workflow” button
  pull_request:                              # runs on any PR that touches an .mq5
    paths:
      - '**/*.mq5'

jobs:
  compile:
    runs-on: windows-latest                  # Microsoft-hosted Windows VM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile all MQ5 files
        uses: fx31337/mql-compile-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # ← leave exactly like this
          init-platform: true        # download & unpack portable MT5 build
          mt-path: mt5-platform      # directory (relative) where MT5 is placed
          path: '.'                  # compile every .mq5 in the repo
          include: '.'               # look for .mqh includes inside the repo
          syntax-only: true          # just check syntax (skip .ex5 artifacts)
          verbose: true              # show full MetaEditor output
