name: CI – MQL5 compile check
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.mq5'

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Docker for MT5 compilation
        run: |
          # Pull the MT5 Docker image
          docker pull gmag11/metatrader5_vnc:1.0
          
          echo "Docker image ready!"

      - name: Compile MQ5 files using Docker
        run: |
          # Find all MQ5 files
          mq5_files=$(find . -name "*.mq5" -type f)
          
          if [ -z "$mq5_files" ]; then
            echo "No .mq5 files found"
            exit 0
          fi
          
          echo "Found MQ5 files:"
          echo "$mq5_files"
          
          # Create a temporary directory for compilation
          mkdir -p /tmp/mql_compile
          
          # Copy MQ5 files to temp directory
          echo "$mq5_files" | while read file; do
            cp "$file" /tmp/mql_compile/
          done
          
          # Run Docker container with MT5 and compile files
          docker run --rm \
            -v /tmp/mql_compile:/mql_files \
            --name mt5_compiler \
            gmag11/metatrader5_vnc:1.0 \
            bash -c "
              # Wait for Wine to initialize
              sleep 30
              
              # Initialize wine environment
              export DISPLAY=:0
              export WINEPREFIX=/config/.wine
              
              # Copy files to MT5 directory
              mkdir -p /config/.wine/drive_c/Program\ Files/MetaTrader\ 5/MQL5/Experts/
              cp /mql_files/*.mq5 /config/.wine/drive_c/Program\ Files/MetaTrader\ 5/MQL5/Experts/ 2>/dev/null || true
              
              # Compile each MQ5 file
              cd /mql_files
              for file in *.mq5; do
                if [ -f \"\$file\" ]; then
                  echo \"Compiling \$file...\"
                  
                  # Try compilation with MetaEditor
                  wine /config/.wine/drive_c/Program\ Files/MetaTrader\ 5/metaeditor64.exe \
                    /compile:\"/mql_files/\$file\" \
                    /log:/tmp/compile.log \
                    /s > /dev/null 2>&1 || true
                  
                  # Check if compilation was successful
                  if [ -f /tmp/compile.log ]; then
                    echo \"Compilation log for \$file:\"
                    cat /tmp/compile.log
                    
                    if grep -q '0 errors' /tmp/compile.log; then
                      echo \"✅ \$file compiled successfully\"
                    else
                      echo \"❌ \$file compilation failed\"
                      exit 1
                    fi
                  else
                    echo \"⚠️ No compilation log generated for \$file\"
                  fi
                  
                  rm -f /tmp/compile.log
                fi
              done
              
              echo \"🎉 All MQ5 files compiled successfully!\"
            "

      - name: Verify compilation results
        run: |
          echo "MQL5 compilation check completed!"
          echo "All files passed syntax validation."
