name: CI – MQL5 compile check
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.mq5'

jobs:
  compile:
    runs-on: windows-latest
    timeout-minutes: 10  # Prevent hanging
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile all MQ5 files
        uses: fx31337/mql-compile-action@v1  # Use v1 which is more stable
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: '.'
          include: '.'
          syntax-only: true
          verbose: true
